/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsCreate } from "../../funcs/integrationsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateIntegrationRequest$inboundSchema,
};

export const tool$integrationsCreate: ToolDefinition<typeof args> = {
  name: "integrations-create",
  description: `Create a new integration.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
