/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsBatchUpsert } from "../../funcs/integrationsBatchUpsert.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.BatchUpsertIntegrationsRequest$inboundSchema,
};

export const tool$integrationsBatchUpsert: ToolDefinition<typeof args> = {
  name: "integrations-batch-upsert",
  description: `Batch upsert a group of integrations`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsBatchUpsert(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
