/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { providerAppsUpdate } from "../../funcs/providerAppsUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateProviderAppRequest$inboundSchema,
};

export const tool$providerAppsUpdate: ToolDefinition<typeof args> = {
  name: "provider-apps-update",
  description: `Update a provider app`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await providerAppsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
