/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GetAcceptEnum, providersGet } from "../funcs/providersGet.js";
import { ListAcceptEnum, providersList } from "../funcs/providersList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { ListAcceptEnum } from "../funcs/providersList.js";

export { GetAcceptEnum } from "../funcs/providersGet.js";

export class Providers extends ClientSDK {
  /**
   * List providers
   */
  async list(
    options?: RequestOptions & { acceptHeaderOverride?: ListAcceptEnum },
  ): Promise<operations.ListProvidersResponse> {
    return unwrapAsync(providersList(
      this,
      options,
    ));
  }

  /**
   * Get provider
   */
  async get(
    request: operations.GetProviderRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetAcceptEnum },
  ): Promise<operations.GetProviderResponse> {
    return unwrapAsync(providersGet(
      this,
      request,
      options,
    ));
  }
}
