/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateGroupRequestBody = {
  /**
   * The ID of the user group that has access to this installation.
   */
  groupRef: string;
  /**
   * The name of the user group that has access to this installation.
   */
  groupName: string;
};

export type CreateGroupRequest = {
  /**
   * The Ampersand project ID or project name.
   */
  projectIdOrName: string;
  requestBody: CreateGroupRequestBody;
};

/**
 * A Problem Details object (RFC 9457).
 *
 * @remarks
 *
 * Additional properties specific to the problem type may be present.
 */
export type CreateGroupAPIProblem = {
  /**
   * An absolute URI that identifies the problem type
   */
  type?: string | undefined;
  /**
   * An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
   */
  href?: string | undefined;
  /**
   * A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
   */
  title?: string | undefined;
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status?: number | undefined;
  /**
   * A human-readable explanation specific to this occurrence of the problem
   */
  detail?: string | undefined;
  /**
   * An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
   */
  instance?: string | undefined;
  /**
   * The subsystem that generated the problem
   */
  subsystem?: string | undefined;
  /**
   * The time the problem occurred, formatted as RFC-3339
   */
  time?: Date | undefined;
  /**
   * A unique identifier for the request, useful for debugging
   */
  requestId?: string | undefined;
  /**
   * A list of problems that caused this problem. This can be used to represent multiple
   *
   * @remarks
   * root causes. There is no guaranteed ordering of the causes.
   */
  causes?: Array<string> | undefined;
  /**
   * A brief description of how to resolve the problem
   */
  remedy?: string | undefined;
  /**
   * An email address to contact for support
   */
  supportEmail?: string | undefined;
  /**
   * A phone number to contact for support
   */
  supportPhone?: string | undefined;
  /**
   * A URL to contact for support
   */
  supportUrl?: string | undefined;
  /**
   * Whether the request can be retried
   */
  retryable?: boolean | undefined;
  /**
   * A timestamp after which the request can be retried, formatted as RFC-3339
   */
  retryAfter?: Date | undefined;
  /**
   * Additional context for the problem
   */
  context?: { [k: string]: any } | undefined;
};

/** @internal */
export const CreateGroupRequestBody$inboundSchema: z.ZodType<
  CreateGroupRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  groupRef: z.string(),
  groupName: z.string(),
});

/** @internal */
export type CreateGroupRequestBody$Outbound = {
  groupRef: string;
  groupName: string;
};

/** @internal */
export const CreateGroupRequestBody$outboundSchema: z.ZodType<
  CreateGroupRequestBody$Outbound,
  z.ZodTypeDef,
  CreateGroupRequestBody
> = z.object({
  groupRef: z.string(),
  groupName: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGroupRequestBody$ {
  /** @deprecated use `CreateGroupRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateGroupRequestBody$inboundSchema;
  /** @deprecated use `CreateGroupRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateGroupRequestBody$outboundSchema;
  /** @deprecated use `CreateGroupRequestBody$Outbound` instead. */
  export type Outbound = CreateGroupRequestBody$Outbound;
}

export function createGroupRequestBodyToJSON(
  createGroupRequestBody: CreateGroupRequestBody,
): string {
  return JSON.stringify(
    CreateGroupRequestBody$outboundSchema.parse(createGroupRequestBody),
  );
}

export function createGroupRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateGroupRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGroupRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGroupRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateGroupRequest$inboundSchema: z.ZodType<
  CreateGroupRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectIdOrName: z.string(),
  RequestBody: z.lazy(() => CreateGroupRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type CreateGroupRequest$Outbound = {
  projectIdOrName: string;
  RequestBody: CreateGroupRequestBody$Outbound;
};

/** @internal */
export const CreateGroupRequest$outboundSchema: z.ZodType<
  CreateGroupRequest$Outbound,
  z.ZodTypeDef,
  CreateGroupRequest
> = z.object({
  projectIdOrName: z.string(),
  requestBody: z.lazy(() => CreateGroupRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGroupRequest$ {
  /** @deprecated use `CreateGroupRequest$inboundSchema` instead. */
  export const inboundSchema = CreateGroupRequest$inboundSchema;
  /** @deprecated use `CreateGroupRequest$outboundSchema` instead. */
  export const outboundSchema = CreateGroupRequest$outboundSchema;
  /** @deprecated use `CreateGroupRequest$Outbound` instead. */
  export type Outbound = CreateGroupRequest$Outbound;
}

export function createGroupRequestToJSON(
  createGroupRequest: CreateGroupRequest,
): string {
  return JSON.stringify(
    CreateGroupRequest$outboundSchema.parse(createGroupRequest),
  );
}

export function createGroupRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateGroupRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGroupRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGroupRequest' from JSON`,
  );
}

/** @internal */
export const CreateGroupAPIProblem$inboundSchema: z.ZodType<
  CreateGroupAPIProblem,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string().default("about:blank"),
  href: z.string().optional(),
  title: z.string().optional(),
  status: z.number().int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  subsystem: z.string().optional(),
  time: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  requestId: z.string().optional(),
  causes: z.array(z.string()).optional(),
  remedy: z.string().optional(),
  supportEmail: z.string().optional(),
  supportPhone: z.string().optional(),
  supportUrl: z.string().optional(),
  retryable: z.boolean().optional(),
  retryAfter: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  context: z.record(z.any()).optional(),
});

/** @internal */
export type CreateGroupAPIProblem$Outbound = {
  type: string;
  href?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;
  subsystem?: string | undefined;
  time?: string | undefined;
  requestId?: string | undefined;
  causes?: Array<string> | undefined;
  remedy?: string | undefined;
  supportEmail?: string | undefined;
  supportPhone?: string | undefined;
  supportUrl?: string | undefined;
  retryable?: boolean | undefined;
  retryAfter?: string | undefined;
  context?: { [k: string]: any } | undefined;
};

/** @internal */
export const CreateGroupAPIProblem$outboundSchema: z.ZodType<
  CreateGroupAPIProblem$Outbound,
  z.ZodTypeDef,
  CreateGroupAPIProblem
> = z.object({
  type: z.string().default("about:blank"),
  href: z.string().optional(),
  title: z.string().optional(),
  status: z.number().int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  subsystem: z.string().optional(),
  time: z.date().transform(v => v.toISOString()).optional(),
  requestId: z.string().optional(),
  causes: z.array(z.string()).optional(),
  remedy: z.string().optional(),
  supportEmail: z.string().optional(),
  supportPhone: z.string().optional(),
  supportUrl: z.string().optional(),
  retryable: z.boolean().optional(),
  retryAfter: z.date().transform(v => v.toISOString()).optional(),
  context: z.record(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGroupAPIProblem$ {
  /** @deprecated use `CreateGroupAPIProblem$inboundSchema` instead. */
  export const inboundSchema = CreateGroupAPIProblem$inboundSchema;
  /** @deprecated use `CreateGroupAPIProblem$outboundSchema` instead. */
  export const outboundSchema = CreateGroupAPIProblem$outboundSchema;
  /** @deprecated use `CreateGroupAPIProblem$Outbound` instead. */
  export type Outbound = CreateGroupAPIProblem$Outbound;
}

export function createGroupAPIProblemToJSON(
  createGroupAPIProblem: CreateGroupAPIProblem,
): string {
  return JSON.stringify(
    CreateGroupAPIProblem$outboundSchema.parse(createGroupAPIProblem),
  );
}

export function createGroupAPIProblemFromJSON(
  jsonString: string,
): SafeParseResult<CreateGroupAPIProblem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGroupAPIProblem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGroupAPIProblem' from JSON`,
  );
}
